"""
Pine Script type checker compatibility layer.

In Pine Script (and PyneCore), every variable is implicitly a Series — meaning even a plain
``float`` supports historical indexing like ``close[1]`` (the previous bar's value). At runtime
the AST transformer handles this, but IDEs (PyCharm, etc.) only see the static types. Since
``Series[float]`` is a transparent alias for ``float`` (see series.pyi), strict type checkers
complain that ``float`` has no ``__getitem__``.

This module solves it by re-exporting ``float``, ``int``, and ``bool`` as enhanced subclasses
**only under TYPE_CHECKING** (i.e., only visible to the IDE, zero runtime cost). The enhanced
versions inherit from their builtins and add ``__getitem__``, so every member of the Series union
becomes indexable in the IDE's eyes.

Usage in @pyne files (via the TypeCheckingStripperTransformer, these are removed at runtime)::

    from typing import TYPE_CHECKING
    if TYPE_CHECKING:
        from pynecore.types.type_checker import *

Or import via ``pine_types`` which re-exports these automatically::

    from pynecore.types import PyneFloat  # already includes the enhanced float

Pyright/basedpyright: set ``"defineConstant": {"TYPECHECKER": "pyright"}`` in pyrightconfig.json
PyCharm: set ``TYPECHECKER=pycharm`` environment variable
"""
import builtins
from typing import Any

TYPECHECKER: str

if TYPECHECKER == "pycharm":
    # The enhanced classes close over arithmetic: every operation returns the
    # enhanced type again. Without this, ``pyne_val + 1.0`` degrades to
    # ``builtins.float``, which PyCharm does not consider assignable back to
    # the enhanced subclass (only literals are), so every arithmetic result
    # stored in a Pyne-aliased slot would be flagged.
    # noinspection PyPep8Naming,PyRedeclaration,PyShadowingBuiltins
    class float(builtins.float):
        def __getitem__(self, index: builtins.int) -> 'float': ...
        def __add__(self, other: Any) -> 'float': ...
        def __radd__(self, other: Any) -> 'float': ...
        def __sub__(self, other: Any) -> 'float': ...
        def __rsub__(self, other: Any) -> 'float': ...
        def __mul__(self, other: Any) -> 'float': ...
        def __rmul__(self, other: Any) -> 'float': ...
        def __truediv__(self, other: Any) -> 'float': ...
        def __rtruediv__(self, other: Any) -> 'float': ...
        def __floordiv__(self, other: Any) -> 'float': ...
        def __rfloordiv__(self, other: Any) -> 'float': ...
        def __mod__(self, other: Any) -> 'float': ...
        def __rmod__(self, other: Any) -> 'float': ...
        def __pow__(self, other: Any, modulo: Any = ...) -> 'float': ...
        def __rpow__(self, other: Any, modulo: Any = ...) -> 'float': ...
        def __neg__(self) -> 'float': ...
        def __pos__(self) -> 'float': ...
        def __abs__(self) -> 'float': ...

    # noinspection PyPep8Naming,PyRedeclaration,PyShadowingBuiltins
    class int(builtins.int):
        def __getitem__(self, index: builtins.int) -> 'int': ...
        def __add__(self, other: builtins.int) -> 'int': ...
        def __radd__(self, other: builtins.int) -> 'int': ...
        def __sub__(self, other: builtins.int) -> 'int': ...
        def __rsub__(self, other: builtins.int) -> 'int': ...
        def __mul__(self, other: builtins.int) -> 'int': ...
        def __rmul__(self, other: builtins.int) -> 'int': ...
        def __truediv__(self, other: builtins.float) -> 'float': ...
        def __rtruediv__(self, other: builtins.float) -> 'float': ...
        def __floordiv__(self, other: builtins.int) -> 'int': ...
        def __rfloordiv__(self, other: builtins.int) -> 'int': ...
        def __mod__(self, other: builtins.int) -> 'int': ...
        def __rmod__(self, other: builtins.int) -> 'int': ...
        def __neg__(self) -> 'int': ...
        def __pos__(self) -> 'int': ...
        def __abs__(self) -> 'int': ...

    # noinspection PyPep8Naming,PyRedeclaration,PyShadowingBuiltins
    class bool(builtins.bool):  # type: ignore
        def __getitem__(self, index: builtins.int) -> builtins.bool: ...

else:
    float = builtins.float
    int = builtins.int
    bool = builtins.bool
